/*Overall statement of a FRAG sentence.*/
FragStatement   ::= Conditions Subject Operator Relationship Measure

Conditions      ::= ('When' EventCondition ';')? ('While' StateConditions ';')?

EventCondition  ::= Variable 'becomes' ( Comparator )? Value

StateConditions ::= (Variable 'is' ( Comparator )* Value ('AND')? )*

Subject         ::= NounPhrase

Operator        ::= ('must' | 'shall' | 'should' | 'may' | 'can')

Relationship    ::= ('have' | 'produce' | 'receive' | 'set') Variable PrepositionalActors

PrepositionalActors ::= (Preposition Actor)*

Actor           ::= NounPhrase

Measures        ::= 'with' ('a(n)' Measurable 'of' Measure (AND)?)+

Measurable      ::= ('value' | 'rate' | 'reaction' | 'range' | OtherMeasurable)

Measure         ::= Comparator Value ('AND' Comparator Value)?

Value           ::= String | Num (Units)?

Variable        ::= NounPhrase

/* FRAG Definitions -> Clauses used to define states and observable (data/energy/material) objects for reuse */

FragDefinition ::= 'Where' Identifier (('is' StateConditions) | ('Has values of' DataDefinition))

DataDefinition ::= 

/* Comparison operators for numerical values */
Comparator      ::= '>' | '<' | '>=' | '<='